### ISSUE TITLE
CFL broken - ichthyop 3.3.3

### ISSUE THREAD

**Issue by stellacoelho** [ichthyop/ichthyop#3]
Hello everyone ! I'm Stellla and I've been currently working with coral dispersion in my master's project. As an input to  Ichthyop I am using ROMS 3D products in a 9km resolution. However I am having problems with the CFL condition as the software keeps me warning that the CFL is broken for W. In fact, it gives me values of W from -3 to 8 approximately, which I understood that is a huge problem for my simulation and so the results of it.

Checking the technical assistance forumon the ichthyop website, I tried different time steps (900s, 600s,300s,150s and even 75s) but the CFL broken warning for W remains. Also, I tried different release zones files to check if it could be the problem, but they're not.

I do have the vertical velocity of ROMS stored as well as the horizontal, but I believe my current configuration of ichthyop does not use the vertical velocities provided by the ocean model...but I didn't know how to confirm it ( I can send the xml configuration file if it's needed).

Thus, I would like to know how I can re-run the Ichthyop with the W provided by ROMS, or if there is another suggestion to solve my problem.  I really appreciate any kind of help you can provide !

Best regards,
Stella.

**Comment by barriern** [comment]
Hi Stella

You are not the first one meeting this problem. It would seem that the problem is due to a misreconstruction of the W velocity by Ichthyop. This potentially leads to unrealistically huge W values, hence the CFL warnings. Reducing the time-steps may be insufficient.

We are currently investigating this issue with some people within the Roms community. In the mean time, could you please send me your configuration file? 

Thanks, 

Nicolas

**Comment by stellacoelho** [comment]
Hello Nicolas, 

thanks for the prompt response! I have already sent you my configuration file by email.

Stella.

**Comment by barriern** [comment]
Hi Stella

Here the configuration file with the two additional parameters that should allow you to activate the reading of W. Note that you need to click on the "Show Hidden parameters". They are hidden by default since these features are not fully tested yet.

Nicolas
[Uploading teste_verao2010_w.zip…]()

**Comment by stellacoelho** [comment]
Hello Nicolas, 

I appreciate all your help ! But I believe something went wrong with the file attached here, I tried opening it but it seems to be empty or for some reason the download does not start....
Could you please attach it again or maybe send it straight for my email ?

Thanks again,
Stella.
