### ISSUE TITLE
Trying to change the study area to some part of the Andaman Sea 

### ISSUE THREAD

**Issue by ChanaChancham** [ichthyop/ichthyop#37]
I try to change the study area to some part of the Andaman Sea. I deal with the simulation failed messages. Would you please give me some guide such as how could tune i the ROMS output or some part of ICHTHYOP ? Now, I attach roms and configue files for you diagnostic.
[Icthythop.zip](https://github.com/ichthyop/ichthyop/files/8058116/Icthythop.zip)
I am waiting for your considered.

Best regards, 
Chana Chancham

**Comment by barriern** [comment]
Hi Chana

I have found the error. Basically, the time in the NetCDF file is not formatted as expected by Ichthyop. 

Basically, Ichthyop expects a `units` attribute in the NetCDF file which should be something like this:
```
seconds since YYYY-MM-DD HH:mm
```

In your case, the unit is just `second`, which causes the code to crash. I just created a patch, which allows to use a user-defined reference time instead of rewritting the Netcdf. 

In order to test it, do you know the time of origin of your NetCDF file?

Thanks,

**Comment by ChanaChancham** [comment]
Hi Nicolus 
Thank you for your diagonostic.  To test please patch time as 2005-01-01 00:00:00. Pleas let me know how todefined reference time.
Thanks,

**Comment by barriern** [comment]
Hi Chana,

It seems to work. Below is a link to a new jar file (the issue will be fixed in the forthcoming 3.3.12 version) and a configuration file, with a hidden parameter "time_origin" which sets the origin of time in a netcdf format. You will need to redefine the paths.

Furthermore, your grid file seems to be corrupted (h is NaN everywhere). Instead I used the values of the `roms-crocoavg.nc` file. 

Let me know if it works, so that I can close the issue.

https://filesender.renater.fr/?s=download&token=39aa0bbe-1d2c-4bab-9036-497a661dddc1

Nicolas

**Comment by ChanaChancham** [comment]
I am sory that late to reply coz I still stuck on failt  ichthyop can't read roms file. Although, I try to change netcdf path, which locat in Windows system as D:\11.Work_Assignment_2021\12.December2021\Crab\ichthyop-master\ichthyop-master\input . 
 Would you please give some comment and analizies.
 Thank you,

**Comment by barriern** [comment]
I will need more infos, like at least an error message or something.
