### ISSUE TITLE
Simulation error due java.datetime.parse on index 4 using ROMS output

### ISSUE THREAD

**Issue by TRasehlomi** [ichthyop/ichthyop#58]
@ barriern

I am using ROMS model output from the following link  [http://dap.saeon.ac.za/thredds/catalog/SAEON.EGAGASINI/2019.Penven/DAILY_MEANS/1_36_degree/catalog.html] to advect particles south of the African continent using the attached configuration file. 

However, I get an error regarding the java.DateTime.Parse on index 4 - please can you assist.

Thanks, TK
[TK_ROMS2d_config_file.txt](https://github.com/ichthyop/ichthyop/files/10468080/TK_ROMS2d_config_file.txt)

**Comment by TRasehlomi** [comment]
@ barriern

**Comment by barriern** [comment]
No need to send me reminders like this. You should know that I am in charge of 3 models and cannot answer immediately to all the messages I receive. Especially when you write during the week end. So please stop this kind of behaviour. 

The error is due to the fact that your Roms file does not meet the standard definition of time units, which should be of the following format:

```
seconds since 1900-01-01 00:00
```

Since it fails from the Netcdf, Ichthyop tries to read the `time_origin` parameter, which must be as follows:

```
seconds since 1990-01-01 00:00
```

Nicolas

**Comment by TRasehlomi** [comment]
Hi, Nicolas.

I am so sorry for this - I didn't mean to be a nuisance.

This won't happen again - I am sorry.

Tshikana
