### ISSUE TITLE
Cannot find more files 

### ISSUE THREAD

**Issue by lgarcia64** [ichthyop/ichthyop#60]
Hi Nicolas,

Im having the issue attached in the Figure below. 
<img width="1336" alt="Screen Shot 2023-01-23 at 12 18 35 PM" src="https://user-images.githubusercontent.com/94406144/214106627-13376819-ab50-484d-890f-4e9679a91bf7.png">

Definitely, there are more files in the folder. Would you mind helping me to solve the issue?? 
Thanks.
-Luisa

**Comment by barriern** [comment]
Hi @lgarcia64 

This error occurs when Ichthyop considers that given the sorting of the file, the last NetCDF time-step of your ocean current dataset has been reached.

One thing you can test is to set the `skip_sorting` parameter to `false` on the `Roms3dDataset` settings. If it works like this, your error is presumably due to a wrong management of time in your input NetCDF.
