### ISSUE TITLE
build old versions of ichthyop

### ISSUE THREAD

**Issue by jesskolbusz** [ichthyop/ichthyop#7]
Hi, I am trying to build an old version of ichthyop with the source code that includes turtle move and swimming orientation. The old .exe/.jar are no longer on the website. How is it possible to build with old source codes? 
Thank you!

**Comment by barriern** [comment]
Hi Jessica

Indeed, executable files are no more available to download since they are pretty heavy and not suitable for versionning.

To build older versions of Ichthyop, you need to download and install Netbeans (https://netbeans.org/). Then you click on `Open Project` and open your Ichthyop folder (you should see a coffe cup as the directory icon). Then you click on `build` and it should work. Tell me if it works. I will update the online documentation to include this.

Nicolas

**Comment by jesskolbusz** [comment]
Yes that works. 
Is it possible to include swimming in a previous version which includes turtlemoving if you include the java files pre compling in netbeans?

**Comment by barriern** [comment]
Not sure to understand your question. But regarding your turtle thing, I have included your files in a specific branch (but the code does not compile yet). I will try to see if I have time to work on it. You provided me with two files (one .java, and one svn-base file), which one should I use?

**Comment by jesskolbusz** [comment]
I'm not sure, I'm assuming just the java? unfortunately not very good at programming java files. They were files passed onto me by Nathan Putman who has completed much of the turtle research using ichthyop in the older versions. For some unknown reason these have not been included in the newer versions. My question above was regarding that version 3 has turtle move action but not swimming action - i think it may be incorporated in there. I feel the capability regarding larvae (not just turtle) swimming AND direction experiments using the turtle direction is very important and worthwhile for scientists
