### ISSUE TITLE
Empty Connectivity matrix plot

### ISSUE THREAD

**Issue by TRasehlomi** [ichthyop/ichthyop#82]
Hello, Nicolas.

I have replicated your connectivity.py script to assess retention and plot connectivity along the west coast of South Africa [30 - 34 deg S] [16 - 18 deg E]. The script runs well but it produces an empty connectivity matrix even in zones where there are particles - is there something I am doing wrong here? I have attached the revised script and associated data (<63 Kb) in this link. https://drive.google.com/drive/folders/1PFHsmgBQHmkZcyWgowlFf0VG_FncWzJk?usp=drive_link

**Comment by TRasehlomi** [comment]
Hi, Nicolas.

I have shared the file with you.

Thanks

**Comment by barriern** [comment]
Hi @TRasehlomi 

I was able to slightly modify your script (cf. enclosed). I think the problem was with some variables that were not available in the output file (which needs clarification).

In your example, I suppose that there is only one release grid. Furthermore, the shape of your retention zones is a bit weird, which may explain why so little particles are within the zones.

Nicolas
[plot_connectivity_TK_NB.pyplot_connectivity_TK_NB.py.txt](https://github.com/ichthyop/ichthyop/files/13338301/plot_connectivity_TK_NB.pyplot_connectivity_TK_NB.py.txt)

**Comment by TRasehlomi** [comment]
Hi, Nicolas.

Thank you for modifying and enhancing the script  - it works perfectly.

Thank you,
Tshikana
