### ISSUE TITLE
Releasing particles from a text file (positions of particles)

### ISSUE THREAD

**Issue by TRasehlomi** [ichthyop/ichthyop#84]
Hi Nicolas,

I am sorry for this novice question -  is there any particular format in which to structure particles positions (lat, lon) in a text file.

I am trying to run simulations from the "benguela_drifters.txt" file (see attached) using one ROMS file from http://dap.saeon.ac.za/thredds/catalog/SAEON.EGAGASINI/2019.Penven/DAILY_MEANS/1_36_degree/catalog.html , but I get the following errors: ichthyop[severe] Index 1 out of bounds for length 1 | java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1.

Thanks,
Tshikana

[benguela_drifters.txt](https://github.com/ichthyop/ichthyop/files/13360720/benguela_drifters.txt)

**Comment by barriern** [comment]
Hi

In your drifter file, you used `,` as decimal, Ichthyop is expecting `.`. Besides, you inverted longitude and latitude. Longitude is the first column, latitude the second one. As a consequence, all your particles are far from your simulation zone.
![release](https://github.com/ichthyop/ichthyop/assets/32549583/7a1113b9-155c-4203-bb6b-edf70341f154)

Here is a corrected release file which seems to work, although some drifters are inland.

[corrected-drifters.txt](https://github.com/ichthyop/ichthyop/files/13365327/corrected-drifters.txt)

I strongly encourage, prior to running a simulation, to plot the model grid and the release drifter locations in order to make sure that everything is all right before running Ichthyop.

Nicolas

**Comment by TRasehlomi** [comment]
Hi Nicolas,

Thank you for the corrected drifter text file - the simulation seems to run
perfectly.

Thank you also for the tip.

Tshikana
