### ISSUE TITLE
Multi-realease "Schedule"

### ISSUE THREAD

**Issue by sidikiba** [ichthyop/ichthyop#9]
Hello,

I made a simulation with the option beginning of simulation.
But we meet that it takes a lot of time.
To go a little fast, I wanted to try with the Schedule option. But I get an error message at the very beginning: **ichthyop [warning] Failed to resize domain | java.io.IOException: Impossible to proportion the simulation area : points out of domain
ichthyop [severe] Java heap space | java.lang.OutOfMemoryError: Java heap space
ichthyop [severe] [Simulation] Initialization failed (performing: SETUP)**
For the "java heap space", I thought it is possible to solve it with java -Xms512m -Xmx1024m . But it doesn't work.

Thank you in advance,

**Comment by barriern** [comment]
Hi Sidiki.

I have tried to run the code using the files you sent by email. I think the error might be due to a wrong parameterization of the `shrink` parameters. In your file, you have:

```
north-west-corner.lat: 22
north-west-corner.lon: -14
south-east-corner.lat: 9
south-east-corner.lon: -22
```

The problem is that you have mixed eastern and southern limits. The proper way to do it is to set:

```
north-west-corner.lon: -22
south-east-corner.lon: -14
```

Tell me if it works for you.

Nicolas

**Comment by sidikiba** [comment]
Hi Nicolas,

Thanks for the answer,
you're right.
Yes, it works well now.

Sidiki
